apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-workload
  namespace: hpa-workload
spec:
  selector:
    matchLabels:
      app: hpa-workload
  template:
    metadata:
      labels:
        app: hpa-workload
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 20m
            memory: 16Mi
