apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eval-hpa
  namespace: flux-merge-eval
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Ignore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eval-target
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
