---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  force: true
  interval: 0m20s
  #dependsOn:
  #  - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/kind-cluster-1
  prune: true
  wait: true
  timeout: 5m0s
  driftDetection:
    ignore:
     - target:
         kind: Deployment
       paths:
       - '/spec/template/spec/containers/0/resources'
       - '/spec/template/spec/containers/1/resources'
       - '/spec/template/spec/containers/2/resources'
       - '/spec/template/spec/containers/3/resources'
