---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  #dependsOn:
  #  - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/kind-cluster-1
  prune: true
  wait: true
  timeout: 5m0s
