---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  force: true
  interval: 0m20s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/kind-reid-1
  prune: true
  wait: true
  timeout: 5m0s
  driftIgnoreRules:
    - paths:
        - "/spec/metrics"
      target:
        kind: HorizontalPodAutoscaler
