apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 0m20s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    redis:
      enabled: true
      repository: public.ecr.aws/docker/library/redis
      tag: 7.0.6
    ingress:
      enabled: true
      className: nginx
  driftDetection:
    mode: enabled
    ignore:
     - target:
         kind: Deployment
       paths:
       - '/spec/template/spec/containers/0/resources'
       - '/spec/template/spec/containers/1/resources'
       - '/spec/template/spec/containers/2/resources'
       - '/spec/template/spec/containers/3/resources'
