apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/flagger
  - ../base/kube-prometheus-stack
  - ../base/podinfo
  - ../base/nginx
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
